# Generated by Django 4.2 on 2025-11-19 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "equipment_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("PUMP", "Pump"),
                            ("MOTOR", "Motor"),
                            ("COMPRESSOR", "Compressor"),
                            ("TURBINE", "Turbine"),
                            ("GENERATOR", "Generator"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("installation_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "Operational"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                            ("OFFLINE", "Offline"),
                        ],
                        default="OPERATIONAL",
                        max_length=20,
                    ),
                ),
                ("last_maintenance", models.DateTimeField(blank=True, null=True)),
                ("next_maintenance", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Equipment",
                "verbose_name_plural": "Equipment",
                "db_table": "equipment",
                "ordering": ["equipment_id"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_key", models.CharField(max_length=100, unique=True)),
                ("config_value", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configurations",
                "db_table": "system_configuration",
            },
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("vibration_x", models.FloatField(help_text="Vibration X-axis (g)")),
                ("vibration_y", models.FloatField(help_text="Vibration Y-axis (g)")),
                ("vibration_z", models.FloatField(help_text="Vibration Z-axis (g)")),
                ("temperature", models.FloatField(help_text="Temperature (°C)")),
                ("current", models.FloatField(help_text="Current (A)")),
                (
                    "vibration_rms",
                    models.FloatField(
                        blank=True, help_text="Root Mean Square of vibration", null=True
                    ),
                ),
                (
                    "vibration_peak",
                    models.FloatField(
                        blank=True, help_text="Peak vibration value", null=True
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_data",
                        to="dashboard.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensor Data",
                "verbose_name_plural": "Sensor Data",
                "db_table": "sensor_data",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "failure_probability",
                    models.FloatField(help_text="Probability of failure (0-1)"),
                ),
                (
                    "health_score",
                    models.FloatField(help_text="Equipment health score (0-100)"),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                            ("FAILURE", "Failure Imminent"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rul_days",
                    models.IntegerField(
                        blank=True, help_text="Remaining Useful Life in days", null=True
                    ),
                ),
                ("model_version", models.CharField(max_length=50)),
                (
                    "confidence_score",
                    models.FloatField(help_text="Model confidence (0-1)"),
                ),
                ("feature_contributions", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="dashboard.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prediction",
                "verbose_name_plural": "Predictions",
                "db_table": "predictions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("PREVENTIVE", "Preventive"),
                            ("CORRECTIVE", "Corrective"),
                            ("PREDICTIVE", "Predictive"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateTimeField()),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField()),
                ("notes", models.TextField(blank=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="dashboard.equipment",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "triggered_by_prediction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.prediction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Log",
                "verbose_name_plural": "Maintenance Logs",
                "db_table": "maintenance_logs",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="dashboard.equipment",
                    ),
                ),
                (
                    "related_prediction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.prediction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
                "db_table": "alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sensordata",
            index=models.Index(
                fields=["equipment", "-timestamp"],
                name="sensor_data_equipme_b1c8cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sensordata",
            index=models.Index(
                fields=["-timestamp"], name="sensor_data_timesta_ac587d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prediction",
            index=models.Index(
                fields=["equipment", "-timestamp"],
                name="predictions_equipme_942b35_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prediction",
            index=models.Index(
                fields=["-timestamp"], name="predictions_timesta_2d843f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["equipment", "-created_at"], name="alerts_equipme_3d4497_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["severity", "-created_at"], name="alerts_severit_03a0f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["is_acknowledged"], name="alerts_is_ackn_a32cbc_idx"
            ),
        ),
    ]
