# Generated by Django 4.2 on 2025-11-30 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("rul", models.FloatField(help_text="Predicted Remaining Useful Life")),
                (
                    "confidence",
                    models.FloatField(help_text="Prediction confidence percentage"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("caution", "Caution"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[("simulated", "Simulated"), ("live", "Live Sensors")],
                        default="simulated",
                        max_length=20,
                    ),
                ),
                ("vibration_health", models.FloatField(default=0)),
                ("temperature_health", models.FloatField(default=0)),
                ("current_health", models.FloatField(default=0)),
                ("average_health", models.FloatField(default=0)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediction_history",
                        to="dashboard.equipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="predictionhistory",
            index=models.Index(
                fields=["equipment", "-timestamp"],
                name="dashboard_p_equipme_1452ac_idx",
            ),
        ),
    ]
